import type { Metadata } from "next";
import "./globals.css";
import { MainLayout } from "@/components/templates";
import { ToastProvider } from "@/context";
import { InitializeToast, Loading, Toast } from "@/components";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loading size="lg" />}>
          <ToastProvider>
            <InitializeToast />
            <MainLayout>{children}</MainLayout>
            <Toast />
          </ToastProvider>
        </Suspense>
      </body>
    </html>
  );
}
